# Generated by Django 4.0.4 on 2022-07-11 19:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleOfBeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тип пива')),
                ('typeOfBeer', models.CharField(choices=[('ALE', 'Эль'), ('LAGER', 'Лагер'), ('OTHERS', 'Другое')], max_length=10, verbose_name='Вид пива')),
            ],
            options={
                'verbose_name': 'Тип пива',
                'verbose_name_plural': 'Типы пива',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('container', models.CharField(choices=[('BOTTLE', 'бутылка'), ('PLASTIC', 'пластиковая бутылка'), ('CAN', 'банка')], max_length=20, verbose_name='Тара')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объём')),
                ('image', models.ImageField(null=True, upload_to='media/images/product', verbose_name='Изображение')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Крепость')),
                ('beerDensity', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Плотность пива')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('inStock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('styleOfBeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.styleofbeer', verbose_name='Тип пива')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Рейтинг')),
                ('body', models.TextField(verbose_name='Тело комментария')),
                ('postAdded', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата комментария')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
