# Generated by Django 4.0.4 on 2022-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='container',
            field=models.CharField(choices=[('BOTTLE', 'бутылка'), ('PLASTIC', 'пластиковая бутылка'), ('CAN', 'банка')], max_length=20, verbose_name='Тара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/product', verbose_name='Изображение'),
        ),
    ]
