# Generated by Django 4.0.4 on 2022-06-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleOfBeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тип пива')),
                ('typeOfBeer', models.CharField(choices=[('ALE', 'Эль'), ('LAGER', 'Лагер')], max_length=10, verbose_name='Вид пива')),
            ],
            options={
                'verbose_name': 'Тип пива',
                'verbose_name_plural': 'Типы пива',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('container', models.CharField(choices=[('BOTTLE', 'бутылка'), ('CAN', 'банка')], max_length=6, verbose_name='Тара')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объём')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Крепость')),
                ('beerDensity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Плотность пива')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('inStock', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('styleOfBeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.styleofbeer', verbose_name='Тип пива')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
