# Generated by Django 4.0.4 on 2022-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthDay',
            field=models.DateField(help_text='формат: 12.05.1990', verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'мужчина'), ('f', 'женщина')], default='', max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNum',
            field=models.CharField(default='+7', max_length=12, verbose_name='номер телефона'),
        ),
    ]
